# Based on https://github.com/anthropics/claude-code-action/blob/main/examples/claude.yml
name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (
        (github.event_name == 'pull_request') ||
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
        (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
      )
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Setup Claude settings with lint hook
        run: |
          chmod +x .github/scripts/setup-claude.sh
          ./.github/scripts/setup-claude.sh

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@6364776f60df0aeb83d4efda5906d68d8cc72137 # beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: 60
          additional_permissions: |
            actions: read
          custom_instructions: |
            You have also been granted tools for editing files and running pnpm commands (fmt, install, lint, test) for testing your changes: pnpm fmt, pnpm install, pnpm lint, pnpm test.

            CRITICAL LINT ERROR POLICY - NO EXCEPTIONS:
            - NEVER abandon a task due to lint errors, regardless of scope or number of violations
            - NEVER suggest limiting scope or accepting partial completion when lint errors exist
            - NEVER comment about "scope expansion" or "out of scope" when facing lint errors
            - When pre-commit hook blocks a commit, you MUST fix ALL lint violations before proceeding
            - Use `pnpm lint --fix` first, then manually fix ALL remaining violations across ALL packages
            - Continue until `pnpm lint` passes completely with zero errors
            - Only after ALL lint checks pass should you attempt to commit
            - DO NOT provide options to "accept current work" or "scope the rule" - just fix the code
            - Your job is complete only when the commit succeeds after passing all checks
          allowed_tools: |
            Bash(pnpm fmt:*),
            Bash(pnpm install),
            Bash(pnpm lint:*),
            Bash(pnpm test:*),
            mcp__github__create_issue,
            mcp__github__add_issue_comment,
            mcp__github__create_pull_request
